// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TeneficGames/podium/client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mocks/podium.go -package=mocks github.com/TeneficGames/podium/client Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	client "github.com/TeneficGames/podium/client"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DeleteLeaderboard mocks base method.
func (m *MockClient) DeleteLeaderboard(ctx context.Context, leaderboard string) (*client.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLeaderboard", ctx, leaderboard)
	ret0, _ := ret[0].(*client.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLeaderboard indicates an expected call of DeleteLeaderboard.
func (mr *MockClientMockRecorder) DeleteLeaderboard(ctx, leaderboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLeaderboard", reflect.TypeOf((*MockClient)(nil).DeleteLeaderboard), ctx, leaderboard)
}

// GetCount mocks base method.
func (m *MockClient) GetCount(ctx context.Context, leaderboard string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", ctx, leaderboard)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockClientMockRecorder) GetCount(ctx, leaderboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockClient)(nil).GetCount), ctx, leaderboard)
}

// GetMember mocks base method.
func (m *MockClient) GetMember(ctx context.Context, leaderboard, memberID string) (*client.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, leaderboard, memberID)
	ret0, _ := ret[0].(*client.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockClientMockRecorder) GetMember(ctx, leaderboard, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockClient)(nil).GetMember), ctx, leaderboard, memberID)
}

// GetMemberInLeaderboards mocks base method.
func (m *MockClient) GetMemberInLeaderboards(ctx context.Context, leaderboards []string, memberID string, order ...string) (*client.ScoreList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, leaderboards, memberID}
	for _, a := range order {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMemberInLeaderboards", varargs...)
	ret0, _ := ret[0].(*client.ScoreList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberInLeaderboards indicates an expected call of GetMemberInLeaderboards.
func (mr *MockClientMockRecorder) GetMemberInLeaderboards(ctx, leaderboards, memberID any, order ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, leaderboards, memberID}, order...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberInLeaderboards", reflect.TypeOf((*MockClient)(nil).GetMemberInLeaderboards), varargs...)
}

// GetMembers mocks base method.
func (m *MockClient) GetMembers(ctx context.Context, leaderboard string, memberIDs []string) (*client.MemberList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, leaderboard, memberIDs)
	ret0, _ := ret[0].(*client.MemberList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockClientMockRecorder) GetMembers(ctx, leaderboard, memberIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockClient)(nil).GetMembers), ctx, leaderboard, memberIDs)
}

// GetMembersAroundMember mocks base method.
func (m *MockClient) GetMembersAroundMember(ctx context.Context, leaderboard, memberID string, pageSize int, getLastIfNotFound bool, order ...string) (*client.MemberList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, leaderboard, memberID, pageSize, getLastIfNotFound}
	for _, a := range order {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMembersAroundMember", varargs...)
	ret0, _ := ret[0].(*client.MemberList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembersAroundMember indicates an expected call of GetMembersAroundMember.
func (mr *MockClientMockRecorder) GetMembersAroundMember(ctx, leaderboard, memberID, pageSize, getLastIfNotFound any, order ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, leaderboard, memberID, pageSize, getLastIfNotFound}, order...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembersAroundMember", reflect.TypeOf((*MockClient)(nil).GetMembersAroundMember), varargs...)
}

// GetTop mocks base method.
func (m *MockClient) GetTop(ctx context.Context, leaderboard string, page, pageSize int) (*client.MemberList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop", ctx, leaderboard, page, pageSize)
	ret0, _ := ret[0].(*client.MemberList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop indicates an expected call of GetTop.
func (mr *MockClientMockRecorder) GetTop(ctx, leaderboard, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop", reflect.TypeOf((*MockClient)(nil).GetTop), ctx, leaderboard, page, pageSize)
}

// GetTopPercent mocks base method.
func (m *MockClient) GetTopPercent(ctx context.Context, leaderboard string, percentage int) (*client.MemberList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPercent", ctx, leaderboard, percentage)
	ret0, _ := ret[0].(*client.MemberList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPercent indicates an expected call of GetTopPercent.
func (mr *MockClientMockRecorder) GetTopPercent(ctx, leaderboard, percentage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPercent", reflect.TypeOf((*MockClient)(nil).GetTopPercent), ctx, leaderboard, percentage)
}

// Healthcheck mocks base method.
func (m *MockClient) Healthcheck(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthcheck", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Healthcheck indicates an expected call of Healthcheck.
func (mr *MockClientMockRecorder) Healthcheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthcheck", reflect.TypeOf((*MockClient)(nil).Healthcheck), ctx)
}

// IncrementScore mocks base method.
func (m *MockClient) IncrementScore(ctx context.Context, leaderboard, memberID string, increment, scoreTTL int) (*client.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementScore", ctx, leaderboard, memberID, increment, scoreTTL)
	ret0, _ := ret[0].(*client.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementScore indicates an expected call of IncrementScore.
func (mr *MockClientMockRecorder) IncrementScore(ctx, leaderboard, memberID, increment, scoreTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementScore", reflect.TypeOf((*MockClient)(nil).IncrementScore), ctx, leaderboard, memberID, increment, scoreTTL)
}

// RemoveMemberFromLeaderboard mocks base method.
func (m *MockClient) RemoveMemberFromLeaderboard(ctx context.Context, leaderboard, member string) (*client.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMemberFromLeaderboard", ctx, leaderboard, member)
	ret0, _ := ret[0].(*client.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveMemberFromLeaderboard indicates an expected call of RemoveMemberFromLeaderboard.
func (mr *MockClientMockRecorder) RemoveMemberFromLeaderboard(ctx, leaderboard, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMemberFromLeaderboard", reflect.TypeOf((*MockClient)(nil).RemoveMemberFromLeaderboard), ctx, leaderboard, member)
}

// UpdateMembersScore mocks base method.
func (m *MockClient) UpdateMembersScore(ctx context.Context, leaderboard string, members []*client.Member, scoreTTL int) (*client.MemberList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembersScore", ctx, leaderboard, members, scoreTTL)
	ret0, _ := ret[0].(*client.MemberList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMembersScore indicates an expected call of UpdateMembersScore.
func (mr *MockClientMockRecorder) UpdateMembersScore(ctx, leaderboard, members, scoreTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembersScore", reflect.TypeOf((*MockClient)(nil).UpdateMembersScore), ctx, leaderboard, members, scoreTTL)
}

// UpdateScore mocks base method.
func (m *MockClient) UpdateScore(ctx context.Context, leaderboard, memberID string, score, scoreTTL int) (*client.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, leaderboard, memberID, score, scoreTTL)
	ret0, _ := ret[0].(*client.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockClientMockRecorder) UpdateScore(ctx, leaderboard, memberID, score, scoreTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockClient)(nil).UpdateScore), ctx, leaderboard, memberID, score, scoreTTL)
}

// UpdateScores mocks base method.
func (m *MockClient) UpdateScores(ctx context.Context, leaderboards []string, memberID string, score, scoreTTL int) (*client.ScoreList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScores", ctx, leaderboards, memberID, score, scoreTTL)
	ret0, _ := ret[0].(*client.ScoreList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScores indicates an expected call of UpdateScores.
func (mr *MockClientMockRecorder) UpdateScores(ctx, leaderboards, memberID, score, scoreTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScores", reflect.TypeOf((*MockClient)(nil).UpdateScores), ctx, leaderboards, memberID, score, scoreTTL)
}
