codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...90"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

ignore:
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "**/*_grpc.pb.go"
  - "**/mocks/**"
  - "**/*_mock.go"
  - "bench/**"
  - "testing/**"
  - "leaderboard/testing/**"
