// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: enrichment/v1/enrichment.proto

package podium_enrichment_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemberEnrichmentService_EnrichMembers_FullMethodName = "/enrichment.v1.MemberEnrichmentService/EnrichMembers"
)

// MemberEnrichmentServiceClient is the client API for MemberEnrichmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemberEnrichmentServiceClient interface {
	// Receives leaderboard members and returns metadata for them.
	EnrichMembers(ctx context.Context, in *EnrichMembersRequest, opts ...grpc.CallOption) (*EnrichMembersResponse, error)
}

type memberEnrichmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberEnrichmentServiceClient(cc grpc.ClientConnInterface) MemberEnrichmentServiceClient {
	return &memberEnrichmentServiceClient{cc}
}

func (c *memberEnrichmentServiceClient) EnrichMembers(ctx context.Context, in *EnrichMembersRequest, opts ...grpc.CallOption) (*EnrichMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichMembersResponse)
	err := c.cc.Invoke(ctx, MemberEnrichmentService_EnrichMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberEnrichmentServiceServer is the server API for MemberEnrichmentService service.
// All implementations must embed UnimplementedMemberEnrichmentServiceServer
// for forward compatibility.
type MemberEnrichmentServiceServer interface {
	// Receives leaderboard members and returns metadata for them.
	EnrichMembers(context.Context, *EnrichMembersRequest) (*EnrichMembersResponse, error)
	mustEmbedUnimplementedMemberEnrichmentServiceServer()
}

// UnimplementedMemberEnrichmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberEnrichmentServiceServer struct{}

func (UnimplementedMemberEnrichmentServiceServer) EnrichMembers(context.Context, *EnrichMembersRequest) (*EnrichMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichMembers not implemented")
}
func (UnimplementedMemberEnrichmentServiceServer) mustEmbedUnimplementedMemberEnrichmentServiceServer() {
}
func (UnimplementedMemberEnrichmentServiceServer) testEmbeddedByValue() {}

// UnsafeMemberEnrichmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberEnrichmentServiceServer will
// result in compilation errors.
type UnsafeMemberEnrichmentServiceServer interface {
	mustEmbedUnimplementedMemberEnrichmentServiceServer()
}

func RegisterMemberEnrichmentServiceServer(s grpc.ServiceRegistrar, srv MemberEnrichmentServiceServer) {
	// If the following call panics, it indicates UnimplementedMemberEnrichmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemberEnrichmentService_ServiceDesc, srv)
}

func _MemberEnrichmentService_EnrichMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberEnrichmentServiceServer).EnrichMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberEnrichmentService_EnrichMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberEnrichmentServiceServer).EnrichMembers(ctx, req.(*EnrichMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemberEnrichmentService_ServiceDesc is the grpc.ServiceDesc for MemberEnrichmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemberEnrichmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enrichment.v1.MemberEnrichmentService",
	HandlerType: (*MemberEnrichmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrichMembers",
			Handler:    _MemberEnrichmentService_EnrichMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enrichment/v1/enrichment.proto",
}
