// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: enrichment/v1/enrichment.proto

package podium_enrichment_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant requesting enrichment.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The leaderboard containing the members.
	LeaderboardId string `protobuf:"bytes,2,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	// The members to enrich.
	Members       []*Member `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichMembersRequest) Reset() {
	*x = EnrichMembersRequest{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichMembersRequest) ProtoMessage() {}

func (x *EnrichMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichMembersRequest.ProtoReflect.Descriptor instead.
func (*EnrichMembersRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichMembersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrichMembersRequest) GetLeaderboardId() string {
	if x != nil {
		return x.LeaderboardId
	}
	return ""
}

func (x *EnrichMembersRequest) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type EnrichMembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The enriched members.
	Members       []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichMembersResponse) Reset() {
	*x = EnrichMembersResponse{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichMembersResponse) ProtoMessage() {}

func (x *EnrichMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichMembersResponse.ProtoReflect.Descriptor instead.
func (*EnrichMembersResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The member's score.
	Score int64 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	// The member's rank in the leaderboard.
	Rank int32 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	// The member's metadata.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Member) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Member) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_enrichment_v1_enrichment_proto protoreflect.FileDescriptor

const file_enrichment_v1_enrichment_proto_rawDesc = "" +
	"\n" +
	"\x1eenrichment/v1/enrichment.proto\x12\renrichment.v1\x1a\x1cgoogle/api/annotations.proto\"\x8b\x01\n" +
	"\x14EnrichMembersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0eleaderboard_id\x18\x02 \x01(\tR\rleaderboardId\x12/\n" +
	"\amembers\x18\x03 \x03(\v2\x15.enrichment.v1.MemberR\amembers\"H\n" +
	"\x15EnrichMembersResponse\x12/\n" +
	"\amembers\x18\x01 \x03(\v2\x15.enrichment.v1.MemberR\amembers\"\xc0\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.enrichment.v1.Member.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x94\x01\n" +
	"\x17MemberEnrichmentService\x12y\n" +
	"\rEnrichMembers\x12#.enrichment.v1.EnrichMembersRequest\x1a$.enrichment.v1.EnrichMembersResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/members/enrichB_Z]github.com/TeneficGames/podium/leaderboard/enriching/proto/enrichment/v1;podium_enrichment_v1b\x06proto3"

var (
	file_enrichment_v1_enrichment_proto_rawDescOnce sync.Once
	file_enrichment_v1_enrichment_proto_rawDescData []byte
)

func file_enrichment_v1_enrichment_proto_rawDescGZIP() []byte {
	file_enrichment_v1_enrichment_proto_rawDescOnce.Do(func() {
		file_enrichment_v1_enrichment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrichment_v1_enrichment_proto_rawDesc), len(file_enrichment_v1_enrichment_proto_rawDesc)))
	})
	return file_enrichment_v1_enrichment_proto_rawDescData
}

var file_enrichment_v1_enrichment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_enrichment_v1_enrichment_proto_goTypes = []any{
	(*EnrichMembersRequest)(nil),  // 0: enrichment.v1.EnrichMembersRequest
	(*EnrichMembersResponse)(nil), // 1: enrichment.v1.EnrichMembersResponse
	(*Member)(nil),                // 2: enrichment.v1.Member
	nil,                           // 3: enrichment.v1.Member.MetadataEntry
}
var file_enrichment_v1_enrichment_proto_depIdxs = []int32{
	2, // 0: enrichment.v1.EnrichMembersRequest.members:type_name -> enrichment.v1.Member
	2, // 1: enrichment.v1.EnrichMembersResponse.members:type_name -> enrichment.v1.Member
	3, // 2: enrichment.v1.Member.metadata:type_name -> enrichment.v1.Member.MetadataEntry
	0, // 3: enrichment.v1.MemberEnrichmentService.EnrichMembers:input_type -> enrichment.v1.EnrichMembersRequest
	1, // 4: enrichment.v1.MemberEnrichmentService.EnrichMembers:output_type -> enrichment.v1.EnrichMembersResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_enrichment_v1_enrichment_proto_init() }
func file_enrichment_v1_enrichment_proto_init() {
	if File_enrichment_v1_enrichment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrichment_v1_enrichment_proto_rawDesc), len(file_enrichment_v1_enrichment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enrichment_v1_enrichment_proto_goTypes,
		DependencyIndexes: file_enrichment_v1_enrichment_proto_depIdxs,
		MessageInfos:      file_enrichment_v1_enrichment_proto_msgTypes,
	}.Build()
	File_enrichment_v1_enrichment_proto = out.File
	file_enrichment_v1_enrichment_proto_goTypes = nil
	file_enrichment_v1_enrichment_proto_depIdxs = nil
}
