{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "podium.fullname" . }}
  labels:
    {{- include "podium.labels" . | nindent 4 }}
spec:
  {{- if ne (toString .Values.podDisruptionBudget.maxUnavailable) "" }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "podium.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}

