apiVersion: v2
name: podium
description: High-performance, Redis-backed leaderboards for games and competitive applications.
type: application
version: 1.0.0
appVersion: "1.0.6"
home: https://github.com/TeneficGames/podium
sources:
  - https://github.com/TeneficGames/podium
maintainers:
  - name: trungdlp
keywords:
  - leaderboard
  - redis
  - grpc
annotations:
  artifacthub.io/license: MIT
