// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: podium/api/v1/podium.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodiumService_HealthCheck_FullMethodName                  = "/podium.api.v1.PodiumService/HealthCheck"
	PodiumService_Status_FullMethodName                       = "/podium.api.v1.PodiumService/Status"
	PodiumService_RemoveLeaderboard_FullMethodName            = "/podium.api.v1.PodiumService/RemoveLeaderboard"
	PodiumService_BulkUpsertScores_FullMethodName             = "/podium.api.v1.PodiumService/BulkUpsertScores"
	PodiumService_UpsertScore_FullMethodName                  = "/podium.api.v1.PodiumService/UpsertScore"
	PodiumService_TotalMembers_FullMethodName                 = "/podium.api.v1.PodiumService/TotalMembers"
	PodiumService_IncrementScore_FullMethodName               = "/podium.api.v1.PodiumService/IncrementScore"
	PodiumService_GetMember_FullMethodName                    = "/podium.api.v1.PodiumService/GetMember"
	PodiumService_GetMembers_FullMethodName                   = "/podium.api.v1.PodiumService/GetMembers"
	PodiumService_RemoveMember_FullMethodName                 = "/podium.api.v1.PodiumService/RemoveMember"
	PodiumService_RemoveMembers_FullMethodName                = "/podium.api.v1.PodiumService/RemoveMembers"
	PodiumService_GetRank_FullMethodName                      = "/podium.api.v1.PodiumService/GetRank"
	PodiumService_GetAroundMember_FullMethodName              = "/podium.api.v1.PodiumService/GetAroundMember"
	PodiumService_GetAroundScore_FullMethodName               = "/podium.api.v1.PodiumService/GetAroundScore"
	PodiumService_GetTopMembers_FullMethodName                = "/podium.api.v1.PodiumService/GetTopMembers"
	PodiumService_GetTopPercentage_FullMethodName             = "/podium.api.v1.PodiumService/GetTopPercentage"
	PodiumService_UpsertScoreMultiLeaderboards_FullMethodName = "/podium.api.v1.PodiumService/UpsertScoreMultiLeaderboards"
	PodiumService_GetRankMultiLeaderboards_FullMethodName     = "/podium.api.v1.PodiumService/GetRankMultiLeaderboards"
)

// PodiumServiceClient is the client API for PodiumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Podium is a service that provides leaderboard functionality.
// Games can manage multiple leaderboards with this service.
type PodiumServiceClient interface {
	// HealthCheck verifies and returns service health.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Status allows to clients to know additional information about Podium execution.
	// Currently only returns error rate of the service.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// RemoveLeaderboard removes a specified leaderboard.
	RemoveLeaderboard(ctx context.Context, in *RemoveLeaderboardRequest, opts ...grpc.CallOption) (*RemoveLeaderboardResponse, error)
	// BulkUpsertScores allows clients to send multiple scores in a single request.
	BulkUpsertScores(ctx context.Context, in *BulkUpsertScoresRequest, opts ...grpc.CallOption) (*BulkUpsertScoresResponse, error)
	// UpsertScore submits a single leaderboard score to Podium.
	UpsertScore(ctx context.Context, in *UpsertScoreRequest, opts ...grpc.CallOption) (*UpsertScoreResponse, error)
	// TotalMembers returns the number of members on a leaderboard.
	TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error)
	// IncrementScore increments a member score.
	IncrementScore(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*IncrementScoreResponse, error)
	// GetMember retrieves leaderboard information from a member.
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error)
	// GetMembers retrieves information about multiple members of a leaderboard.
	GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*GetMembersResponse, error)
	// RemoveMember removes a member from a leaderboard.
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	// RemoveMembers allows the removal of multiple members of a leaderboard.
	RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*RemoveMembersResponse, error)
	// GetRank retrieves ranking information about a member.
	GetRank(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*GetRankResponse, error)
	// GetAroundMember retrieves the closest members to another member on the leaderboard.
	GetAroundMember(ctx context.Context, in *GetAroundMemberRequest, opts ...grpc.CallOption) (*GetAroundMemberResponse, error)
	// GetAroundScore retrieves the closest members to a score on the leaderboard.
	GetAroundScore(ctx context.Context, in *GetAroundScoreRequest, opts ...grpc.CallOption) (*GetAroundScoreResponse, error)
	// GetTopMembers retrieves the top ranking members of a leaderboard.
	GetTopMembers(ctx context.Context, in *GetTopMembersRequest, opts ...grpc.CallOption) (*GetTopMembersResponse, error)
	// GetTopPercentage retrieves a percentage of the top members of the leaderboard.
	GetTopPercentage(ctx context.Context, in *GetTopPercentageRequest, opts ...grpc.CallOption) (*GetTopPercentageResponse, error)
	// UpsertScoreMultiLeaderboards sends a member score to multiple leaderboards.
	UpsertScoreMultiLeaderboards(ctx context.Context, in *UpsertScoreMultiLeaderboardsRequest, opts ...grpc.CallOption) (*UpsertScoreMultiLeaderboardsResponse, error)
	// GetRankMultiLeaderboards retrieves information about a member in multiple leaderboards.
	GetRankMultiLeaderboards(ctx context.Context, in *GetRankMultiLeaderboardsRequest, opts ...grpc.CallOption) (*GetRankMultiLeaderboardsResponse, error)
}

type podiumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodiumServiceClient(cc grpc.ClientConnInterface) PodiumServiceClient {
	return &podiumServiceClient{cc}
}

func (c *podiumServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PodiumService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PodiumService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) RemoveLeaderboard(ctx context.Context, in *RemoveLeaderboardRequest, opts ...grpc.CallOption) (*RemoveLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveLeaderboardResponse)
	err := c.cc.Invoke(ctx, PodiumService_RemoveLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) BulkUpsertScores(ctx context.Context, in *BulkUpsertScoresRequest, opts ...grpc.CallOption) (*BulkUpsertScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkUpsertScoresResponse)
	err := c.cc.Invoke(ctx, PodiumService_BulkUpsertScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) UpsertScore(ctx context.Context, in *UpsertScoreRequest, opts ...grpc.CallOption) (*UpsertScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertScoreResponse)
	err := c.cc.Invoke(ctx, PodiumService_UpsertScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) TotalMembers(ctx context.Context, in *TotalMembersRequest, opts ...grpc.CallOption) (*TotalMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotalMembersResponse)
	err := c.cc.Invoke(ctx, PodiumService_TotalMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) IncrementScore(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*IncrementScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementScoreResponse)
	err := c.cc.Invoke(ctx, PodiumService_IncrementScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*GetMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembersResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, PodiumService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*RemoveMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMembersResponse)
	err := c.cc.Invoke(ctx, PodiumService_RemoveMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetRank(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*GetRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRankResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetAroundMember(ctx context.Context, in *GetAroundMemberRequest, opts ...grpc.CallOption) (*GetAroundMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAroundMemberResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetAroundMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetAroundScore(ctx context.Context, in *GetAroundScoreRequest, opts ...grpc.CallOption) (*GetAroundScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAroundScoreResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetAroundScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetTopMembers(ctx context.Context, in *GetTopMembersRequest, opts ...grpc.CallOption) (*GetTopMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopMembersResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetTopMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetTopPercentage(ctx context.Context, in *GetTopPercentageRequest, opts ...grpc.CallOption) (*GetTopPercentageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopPercentageResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetTopPercentage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) UpsertScoreMultiLeaderboards(ctx context.Context, in *UpsertScoreMultiLeaderboardsRequest, opts ...grpc.CallOption) (*UpsertScoreMultiLeaderboardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertScoreMultiLeaderboardsResponse)
	err := c.cc.Invoke(ctx, PodiumService_UpsertScoreMultiLeaderboards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podiumServiceClient) GetRankMultiLeaderboards(ctx context.Context, in *GetRankMultiLeaderboardsRequest, opts ...grpc.CallOption) (*GetRankMultiLeaderboardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRankMultiLeaderboardsResponse)
	err := c.cc.Invoke(ctx, PodiumService_GetRankMultiLeaderboards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodiumServiceServer is the server API for PodiumService service.
// All implementations must embed UnimplementedPodiumServiceServer
// for forward compatibility.
//
// Podium is a service that provides leaderboard functionality.
// Games can manage multiple leaderboards with this service.
type PodiumServiceServer interface {
	// HealthCheck verifies and returns service health.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Status allows to clients to know additional information about Podium execution.
	// Currently only returns error rate of the service.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// RemoveLeaderboard removes a specified leaderboard.
	RemoveLeaderboard(context.Context, *RemoveLeaderboardRequest) (*RemoveLeaderboardResponse, error)
	// BulkUpsertScores allows clients to send multiple scores in a single request.
	BulkUpsertScores(context.Context, *BulkUpsertScoresRequest) (*BulkUpsertScoresResponse, error)
	// UpsertScore submits a single leaderboard score to Podium.
	UpsertScore(context.Context, *UpsertScoreRequest) (*UpsertScoreResponse, error)
	// TotalMembers returns the number of members on a leaderboard.
	TotalMembers(context.Context, *TotalMembersRequest) (*TotalMembersResponse, error)
	// IncrementScore increments a member score.
	IncrementScore(context.Context, *IncrementScoreRequest) (*IncrementScoreResponse, error)
	// GetMember retrieves leaderboard information from a member.
	GetMember(context.Context, *GetMemberRequest) (*GetMemberResponse, error)
	// GetMembers retrieves information about multiple members of a leaderboard.
	GetMembers(context.Context, *GetMembersRequest) (*GetMembersResponse, error)
	// RemoveMember removes a member from a leaderboard.
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	// RemoveMembers allows the removal of multiple members of a leaderboard.
	RemoveMembers(context.Context, *RemoveMembersRequest) (*RemoveMembersResponse, error)
	// GetRank retrieves ranking information about a member.
	GetRank(context.Context, *GetRankRequest) (*GetRankResponse, error)
	// GetAroundMember retrieves the closest members to another member on the leaderboard.
	GetAroundMember(context.Context, *GetAroundMemberRequest) (*GetAroundMemberResponse, error)
	// GetAroundScore retrieves the closest members to a score on the leaderboard.
	GetAroundScore(context.Context, *GetAroundScoreRequest) (*GetAroundScoreResponse, error)
	// GetTopMembers retrieves the top ranking members of a leaderboard.
	GetTopMembers(context.Context, *GetTopMembersRequest) (*GetTopMembersResponse, error)
	// GetTopPercentage retrieves a percentage of the top members of the leaderboard.
	GetTopPercentage(context.Context, *GetTopPercentageRequest) (*GetTopPercentageResponse, error)
	// UpsertScoreMultiLeaderboards sends a member score to multiple leaderboards.
	UpsertScoreMultiLeaderboards(context.Context, *UpsertScoreMultiLeaderboardsRequest) (*UpsertScoreMultiLeaderboardsResponse, error)
	// GetRankMultiLeaderboards retrieves information about a member in multiple leaderboards.
	GetRankMultiLeaderboards(context.Context, *GetRankMultiLeaderboardsRequest) (*GetRankMultiLeaderboardsResponse, error)
	mustEmbedUnimplementedPodiumServiceServer()
}

// UnimplementedPodiumServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodiumServiceServer struct{}

func (UnimplementedPodiumServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPodiumServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPodiumServiceServer) RemoveLeaderboard(context.Context, *RemoveLeaderboardRequest) (*RemoveLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveLeaderboard not implemented")
}
func (UnimplementedPodiumServiceServer) BulkUpsertScores(context.Context, *BulkUpsertScoresRequest) (*BulkUpsertScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkUpsertScores not implemented")
}
func (UnimplementedPodiumServiceServer) UpsertScore(context.Context, *UpsertScoreRequest) (*UpsertScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertScore not implemented")
}
func (UnimplementedPodiumServiceServer) TotalMembers(context.Context, *TotalMembersRequest) (*TotalMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TotalMembers not implemented")
}
func (UnimplementedPodiumServiceServer) IncrementScore(context.Context, *IncrementScoreRequest) (*IncrementScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementScore not implemented")
}
func (UnimplementedPodiumServiceServer) GetMember(context.Context, *GetMemberRequest) (*GetMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMember not implemented")
}
func (UnimplementedPodiumServiceServer) GetMembers(context.Context, *GetMembersRequest) (*GetMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembers not implemented")
}
func (UnimplementedPodiumServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedPodiumServiceServer) RemoveMembers(context.Context, *RemoveMembersRequest) (*RemoveMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMembers not implemented")
}
func (UnimplementedPodiumServiceServer) GetRank(context.Context, *GetRankRequest) (*GetRankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRank not implemented")
}
func (UnimplementedPodiumServiceServer) GetAroundMember(context.Context, *GetAroundMemberRequest) (*GetAroundMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAroundMember not implemented")
}
func (UnimplementedPodiumServiceServer) GetAroundScore(context.Context, *GetAroundScoreRequest) (*GetAroundScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAroundScore not implemented")
}
func (UnimplementedPodiumServiceServer) GetTopMembers(context.Context, *GetTopMembersRequest) (*GetTopMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopMembers not implemented")
}
func (UnimplementedPodiumServiceServer) GetTopPercentage(context.Context, *GetTopPercentageRequest) (*GetTopPercentageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopPercentage not implemented")
}
func (UnimplementedPodiumServiceServer) UpsertScoreMultiLeaderboards(context.Context, *UpsertScoreMultiLeaderboardsRequest) (*UpsertScoreMultiLeaderboardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertScoreMultiLeaderboards not implemented")
}
func (UnimplementedPodiumServiceServer) GetRankMultiLeaderboards(context.Context, *GetRankMultiLeaderboardsRequest) (*GetRankMultiLeaderboardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRankMultiLeaderboards not implemented")
}
func (UnimplementedPodiumServiceServer) mustEmbedUnimplementedPodiumServiceServer() {}
func (UnimplementedPodiumServiceServer) testEmbeddedByValue()                       {}

// UnsafePodiumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodiumServiceServer will
// result in compilation errors.
type UnsafePodiumServiceServer interface {
	mustEmbedUnimplementedPodiumServiceServer()
}

func RegisterPodiumServiceServer(s grpc.ServiceRegistrar, srv PodiumServiceServer) {
	// If the following call panics, it indicates UnimplementedPodiumServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodiumService_ServiceDesc, srv)
}

func _PodiumService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_RemoveLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).RemoveLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_RemoveLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).RemoveLeaderboard(ctx, req.(*RemoveLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_BulkUpsertScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpsertScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).BulkUpsertScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_BulkUpsertScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).BulkUpsertScores(ctx, req.(*BulkUpsertScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_UpsertScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).UpsertScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_UpsertScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).UpsertScore(ctx, req.(*UpsertScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_TotalMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).TotalMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_TotalMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).TotalMembers(ctx, req.(*TotalMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_IncrementScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).IncrementScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_IncrementScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).IncrementScore(ctx, req.(*IncrementScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetMembers(ctx, req.(*GetMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_RemoveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).RemoveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_RemoveMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).RemoveMembers(ctx, req.(*RemoveMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetRank(ctx, req.(*GetRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetAroundMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAroundMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetAroundMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetAroundMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetAroundMember(ctx, req.(*GetAroundMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetAroundScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAroundScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetAroundScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetAroundScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetAroundScore(ctx, req.(*GetAroundScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetTopMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetTopMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetTopMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetTopMembers(ctx, req.(*GetTopMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetTopPercentage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopPercentageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetTopPercentage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetTopPercentage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetTopPercentage(ctx, req.(*GetTopPercentageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_UpsertScoreMultiLeaderboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertScoreMultiLeaderboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).UpsertScoreMultiLeaderboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_UpsertScoreMultiLeaderboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).UpsertScoreMultiLeaderboards(ctx, req.(*UpsertScoreMultiLeaderboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodiumService_GetRankMultiLeaderboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankMultiLeaderboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodiumServiceServer).GetRankMultiLeaderboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodiumService_GetRankMultiLeaderboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodiumServiceServer).GetRankMultiLeaderboards(ctx, req.(*GetRankMultiLeaderboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodiumService_ServiceDesc is the grpc.ServiceDesc for PodiumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodiumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podium.api.v1.PodiumService",
	HandlerType: (*PodiumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PodiumService_HealthCheck_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _PodiumService_Status_Handler,
		},
		{
			MethodName: "RemoveLeaderboard",
			Handler:    _PodiumService_RemoveLeaderboard_Handler,
		},
		{
			MethodName: "BulkUpsertScores",
			Handler:    _PodiumService_BulkUpsertScores_Handler,
		},
		{
			MethodName: "UpsertScore",
			Handler:    _PodiumService_UpsertScore_Handler,
		},
		{
			MethodName: "TotalMembers",
			Handler:    _PodiumService_TotalMembers_Handler,
		},
		{
			MethodName: "IncrementScore",
			Handler:    _PodiumService_IncrementScore_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _PodiumService_GetMember_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _PodiumService_GetMembers_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _PodiumService_RemoveMember_Handler,
		},
		{
			MethodName: "RemoveMembers",
			Handler:    _PodiumService_RemoveMembers_Handler,
		},
		{
			MethodName: "GetRank",
			Handler:    _PodiumService_GetRank_Handler,
		},
		{
			MethodName: "GetAroundMember",
			Handler:    _PodiumService_GetAroundMember_Handler,
		},
		{
			MethodName: "GetAroundScore",
			Handler:    _PodiumService_GetAroundScore_Handler,
		},
		{
			MethodName: "GetTopMembers",
			Handler:    _PodiumService_GetTopMembers_Handler,
		},
		{
			MethodName: "GetTopPercentage",
			Handler:    _PodiumService_GetTopPercentage_Handler,
		},
		{
			MethodName: "UpsertScoreMultiLeaderboards",
			Handler:    _PodiumService_UpsertScoreMultiLeaderboards_Handler,
		},
		{
			MethodName: "GetRankMultiLeaderboards",
			Handler:    _PodiumService_GetRankMultiLeaderboards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podium/api/v1/podium.proto",
}
