healthcheck:
  workingText: WORKING

redis:
  cluster:
    enabled: false
  addrs: "localhost:5000"
  host: localhost
  port: 6379
  password: ""
  db: 0
  connectionTimeout: 200

api:
  maxReturnedMembers: 2000
  maxReadBufferSize: 80240

worker:
  expirationCheckInterval: 60s
  expirationLimitPerRun: 1000

enrichment:
  providers:
  cache:
    ttl: 24h
    addr: ""
    password: ""
  request_timeout: 500ms
