healthcheck:
  workingText: WORKING

redis:
  addrs: "localhost:5000"
  host: localhost
  port: 6379
  db: 0

faultyRedis:
  host: "localhost"
  port: 12345
  db: 0

api:
  maxReturnedMembers: 2000

worker:
  expirationCheckInterval: 1s
  expirationLimitPerRun: 100
