// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: leaderboard/enriching/proto/webhook/v1/podium_webhook.proto

package podium_leaderboard_webhooks_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderboardsEnrichmentService_EnrichLeaderboards_FullMethodName = "/LeaderboardsEnrichmentService/EnrichLeaderboards"
)

// LeaderboardsEnrichmentServiceClient is the client API for LeaderboardsEnrichmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderboardsEnrichmentServiceClient interface {
	// Receives an array of members and returns the same array enriched with
	// the member's metadata.
	EnrichLeaderboards(ctx context.Context, in *EnrichLeaderboardsRequest, opts ...grpc.CallOption) (*EnrichLeaderboardsResponse, error)
}

type leaderboardsEnrichmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderboardsEnrichmentServiceClient(cc grpc.ClientConnInterface) LeaderboardsEnrichmentServiceClient {
	return &leaderboardsEnrichmentServiceClient{cc}
}

func (c *leaderboardsEnrichmentServiceClient) EnrichLeaderboards(ctx context.Context, in *EnrichLeaderboardsRequest, opts ...grpc.CallOption) (*EnrichLeaderboardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichLeaderboardsResponse)
	err := c.cc.Invoke(ctx, LeaderboardsEnrichmentService_EnrichLeaderboards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderboardsEnrichmentServiceServer is the server API for LeaderboardsEnrichmentService service.
// All implementations must embed UnimplementedLeaderboardsEnrichmentServiceServer
// for forward compatibility.
type LeaderboardsEnrichmentServiceServer interface {
	// Receives an array of members and returns the same array enriched with
	// the member's metadata.
	EnrichLeaderboards(context.Context, *EnrichLeaderboardsRequest) (*EnrichLeaderboardsResponse, error)
	mustEmbedUnimplementedLeaderboardsEnrichmentServiceServer()
}

// UnimplementedLeaderboardsEnrichmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderboardsEnrichmentServiceServer struct{}

func (UnimplementedLeaderboardsEnrichmentServiceServer) EnrichLeaderboards(context.Context, *EnrichLeaderboardsRequest) (*EnrichLeaderboardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichLeaderboards not implemented")
}
func (UnimplementedLeaderboardsEnrichmentServiceServer) mustEmbedUnimplementedLeaderboardsEnrichmentServiceServer() {
}
func (UnimplementedLeaderboardsEnrichmentServiceServer) testEmbeddedByValue() {}

// UnsafeLeaderboardsEnrichmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderboardsEnrichmentServiceServer will
// result in compilation errors.
type UnsafeLeaderboardsEnrichmentServiceServer interface {
	mustEmbedUnimplementedLeaderboardsEnrichmentServiceServer()
}

func RegisterLeaderboardsEnrichmentServiceServer(s grpc.ServiceRegistrar, srv LeaderboardsEnrichmentServiceServer) {
	// If the following call panics, it indicates UnimplementedLeaderboardsEnrichmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderboardsEnrichmentService_ServiceDesc, srv)
}

func _LeaderboardsEnrichmentService_EnrichLeaderboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichLeaderboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsEnrichmentServiceServer).EnrichLeaderboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsEnrichmentService_EnrichLeaderboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsEnrichmentServiceServer).EnrichLeaderboards(ctx, req.(*EnrichLeaderboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderboardsEnrichmentService_ServiceDesc is the grpc.ServiceDesc for LeaderboardsEnrichmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderboardsEnrichmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LeaderboardsEnrichmentService",
	HandlerType: (*LeaderboardsEnrichmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrichLeaderboards",
			Handler:    _LeaderboardsEnrichmentService_EnrichLeaderboards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaderboard/enriching/proto/webhook/v1/podium_webhook.proto",
}
