// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: webhook/v1/podium_webhook.proto

package podium_leaderboard_webhooks_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichLeaderboardsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The members to enrich.
	Members       []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichLeaderboardsRequest) Reset() {
	*x = EnrichLeaderboardsRequest{}
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichLeaderboardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichLeaderboardsRequest) ProtoMessage() {}

func (x *EnrichLeaderboardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichLeaderboardsRequest.ProtoReflect.Descriptor instead.
func (*EnrichLeaderboardsRequest) Descriptor() ([]byte, []int) {
	return file_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichLeaderboardsRequest) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type EnrichLeaderboardsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The enriched members.
	Members       []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichLeaderboardsResponse) Reset() {
	*x = EnrichLeaderboardsResponse{}
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichLeaderboardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichLeaderboardsResponse) ProtoMessage() {}

func (x *EnrichLeaderboardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichLeaderboardsResponse.ProtoReflect.Descriptor instead.
func (*EnrichLeaderboardsResponse) Descriptor() ([]byte, []int) {
	return file_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichLeaderboardsResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The leaderboard's ID.
	LeaderboardId string `protobuf:"bytes,1,opt,name=leaderboard_id,json=leaderboardId,proto3" json:"leaderboard_id,omitempty"`
	// The member's ID.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The member's scores.
	Scores []*Score `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	// The member's rank in the leaderboard.
	Rank int32 `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	// The member's metadata.
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetLeaderboardId() string {
	if x != nil {
		return x.LeaderboardId
	}
	return ""
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *Member) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Member) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Score struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The score value.
	Value         int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_podium_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_webhook_v1_podium_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *Score) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_webhook_v1_podium_webhook_proto protoreflect.FileDescriptor

const file_webhook_v1_podium_webhook_proto_rawDesc = "" +
	"\n" +
	"\x1fwebhook/v1/podium_webhook.proto\x12\n" +
	"webhook.v1\x1a\x1cgoogle/api/annotations.proto\"I\n" +
	"\x19EnrichLeaderboardsRequest\x12,\n" +
	"\amembers\x18\x01 \x03(\v2\x12.webhook.v1.MemberR\amembers\"J\n" +
	"\x1aEnrichLeaderboardsResponse\x12,\n" +
	"\amembers\x18\x01 \x03(\v2\x12.webhook.v1.MemberR\amembers\"\xf9\x01\n" +
	"\x06Member\x12%\n" +
	"\x0eleaderboard_id\x18\x01 \x01(\tR\rleaderboardId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12)\n" +
	"\x06scores\x18\x03 \x03(\v2\x11.webhook.v1.ScoreR\x06scores\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .webhook.v1.Member.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1d\n" +
	"\x05Score\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value2\xaf\x01\n" +
	"\x1dLeaderboardsEnrichmentService\x12\x8d\x01\n" +
	"\x12EnrichLeaderboards\x12%.webhook.v1.EnrichLeaderboardsRequest\x1a&.webhook.v1.EnrichLeaderboardsResponse\"(\x82\xd3\xe4\x93\x02\":\amembers\"\x17/v1/leaderboards/enrichBfZdgithub.com/TeneficGames/podium/leaderboard/enriching/proto/webhook/v1;podium_leaderboard_webhooks_v1b\x06proto3"

var (
	file_webhook_v1_podium_webhook_proto_rawDescOnce sync.Once
	file_webhook_v1_podium_webhook_proto_rawDescData []byte
)

func file_webhook_v1_podium_webhook_proto_rawDescGZIP() []byte {
	file_webhook_v1_podium_webhook_proto_rawDescOnce.Do(func() {
		file_webhook_v1_podium_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhook_v1_podium_webhook_proto_rawDesc), len(file_webhook_v1_podium_webhook_proto_rawDesc)))
	})
	return file_webhook_v1_podium_webhook_proto_rawDescData
}

var file_webhook_v1_podium_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_webhook_v1_podium_webhook_proto_goTypes = []any{
	(*EnrichLeaderboardsRequest)(nil),  // 0: webhook.v1.EnrichLeaderboardsRequest
	(*EnrichLeaderboardsResponse)(nil), // 1: webhook.v1.EnrichLeaderboardsResponse
	(*Member)(nil),                     // 2: webhook.v1.Member
	(*Score)(nil),                      // 3: webhook.v1.Score
	nil,                                // 4: webhook.v1.Member.MetadataEntry
}
var file_webhook_v1_podium_webhook_proto_depIdxs = []int32{
	2, // 0: webhook.v1.EnrichLeaderboardsRequest.members:type_name -> webhook.v1.Member
	2, // 1: webhook.v1.EnrichLeaderboardsResponse.members:type_name -> webhook.v1.Member
	3, // 2: webhook.v1.Member.scores:type_name -> webhook.v1.Score
	4, // 3: webhook.v1.Member.metadata:type_name -> webhook.v1.Member.MetadataEntry
	0, // 4: webhook.v1.LeaderboardsEnrichmentService.EnrichLeaderboards:input_type -> webhook.v1.EnrichLeaderboardsRequest
	1, // 5: webhook.v1.LeaderboardsEnrichmentService.EnrichLeaderboards:output_type -> webhook.v1.EnrichLeaderboardsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_webhook_v1_podium_webhook_proto_init() }
func file_webhook_v1_podium_webhook_proto_init() {
	if File_webhook_v1_podium_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhook_v1_podium_webhook_proto_rawDesc), len(file_webhook_v1_podium_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhook_v1_podium_webhook_proto_goTypes,
		DependencyIndexes: file_webhook_v1_podium_webhook_proto_depIdxs,
		MessageInfos:      file_webhook_v1_podium_webhook_proto_msgTypes,
	}.Build()
	File_webhook_v1_podium_webhook_proto = out.File
	file_webhook_v1_podium_webhook_proto_goTypes = nil
	file_webhook_v1_podium_webhook_proto_depIdxs = nil
}
